use dd_ftp_core::{ConnectionInfo, FileEntry, TransferJob};
use uuid::Uuid;

use crate::{ChoicePromptKind, FocusPane, OverwritePolicy, SelectPolicy};

#[derive(Debug)]
pub enum Action {
    Connect(ConnectionInfo),
    Disconnect,
    SetConnected(bool),
    SetLocalEntries {
        entries: Vec<FileEntry>,
        select: SelectPolicy,
    },
    SetRemoteEntries {
        entries: Vec<FileEntry>,
        select: SelectPolicy,
    },
    SetBookmarks(Vec<ConnectionInfo>),
    SelectNextBookmark,
    SelectPrevBookmark,
    ToggleQuickConnect,
    ToggleBookmarks,
    QuickConnectNextField,
    QuickConnectPrevField,
    QuickConnectInput(char),
    QuickConnectBackspace,
    QuickConnectSyncField,
    QuickConnectBeginSelect(usize),
    QuickConnectExtendSelect(usize),
    QuickConnectMoveCursor {
        dir: i32,
        shift: bool,
    },
    QuickConnectSetProtocolNext,
    QuickConnectSetProtocolPrev,
    QuickConnectSetFromBookmark(ConnectionInfo),
    OpenKeyPicker {
        cwd: String,
        entries: Vec<FileEntry>,
        prefer: Option<String>,
    },
    CloseKeyPicker,
    SetKeyPickerEntries {
        cwd: String,
        entries: Vec<FileEntry>,
        select: SelectPolicy,
        prefer: Option<String>,
    },
    KeyPickerSelectUp,
    KeyPickerSelectDown,
    KeyPickerSelectIndex(usize),
    KeyPickerConfirm,
    QueueTransfer(TransferJob),
    StartNextTransfer,
    MarkTransferCompleted(TransferJob),
    MarkTransferFailed(TransferJob),
    MarkTransferCancelled(TransferJob),
    RetryLastFailed,
    UpdateTransferProgress {
        job_id: Uuid,
        transferred_bytes: u64,
        size_bytes: Option<u64>,
    },
    ClearPendingTransfers,
    SetWorkerView {
        active_count: usize,
        running: bool,
        cancel_requested: bool,
    },
    SetStatus(String),
    SetBusy(bool),
    ShowError(String),
    ClearError,
    SetFocus(FocusPane),
    SelectIndex {
        pane: FocusPane,
        index: usize,
    },
    HelpScroll(i32),
    QueueScroll(i32),
    FocusNextPane,
    ToggleHelp,
    ToggleThemeDebug,
    SelectUp,
    SelectDown,
    ToggleFilter,
    FilterInput(char),
    FilterBackspace,
    ClearFilter,
    ToggleCompare,
    CreateFile(String),
    CreateFolder(String),
    RenameItem(String, String),
    DeleteItem(String),
    ShowCreatePrompt,
    ShowRenamePrompt,
    ShowChmodPrompt {
        mode: String,
    },
    ShowDeletePrompt,
    ShowChoicePrompt(ChoicePromptKind),
    ToggleMark,
    ClearMarks {
        pane: FocusPane,
    },
    CycleSort,
    ToggleSortDir,
    ToggleHideDotfiles,
    SetOverwritePolicy(OverwritePolicy),
    PromptInput(char),
    PromptBackspace,
    ConfirmPrompt,
    CancelPrompt,
}
