use dd_ftp_core::{ConnectionInfo, FileEntry, TransferJob};
use uuid::Uuid;

#[derive(Debug)]
pub enum Action {
    Connect(ConnectionInfo),
    Disconnect,
    SetConnected(bool),
    SetLocalEntries(Vec<FileEntry>),
    SetRemoteEntries(Vec<FileEntry>),
    SetBookmarks(Vec<ConnectionInfo>),
    SelectNextBookmark,
    SelectPrevBookmark,
    ToggleQuickConnect,
    ToggleBookmarks,
    QuickConnectNextField,
    QuickConnectPrevField,
    QuickConnectInput(char),
    QuickConnectBackspace,
    QuickConnectSetProtocolNext,
    QuickConnectSetProtocolPrev,
    QuickConnectSetFromBookmark(ConnectionInfo),
    QueueTransfer(TransferJob),
    StartNextTransfer,
    MarkTransferCompleted(TransferJob),
    MarkTransferFailed(TransferJob),
    MarkTransferCancelled(TransferJob),
    RetryLastFailed,
    UpdateTransferProgress {
        job_id: Uuid,
        transferred_bytes: u64,
        size_bytes: Option<u64>,
    },
    ClearPendingTransfers,
    SetStatus(String),
    ShowError(String),
    ClearError,
    FocusNextPane,
    ToggleHelp,
    ToggleThemeDebug,
    SelectUp,
    SelectDown,
    ToggleFilter,
    FilterInput(char),
    FilterBackspace,
    ClearFilter,
    ToggleCompare,
    CreateFile(String),
    CreateFolder(String),
    RenameItem(String, String),
    DeleteItem(String),
    ShowCreatePrompt,
    ShowRenamePrompt,
    ShowDeletePrompt,
    PromptInput(char),
    PromptBackspace,
    ConfirmPrompt,
    CancelPrompt,
}
